// <auto-generated />
using System;
using DiscountDemo.Adapter.EfDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscountDemo.Adapter.EfDataAccess.Migrations
{
    [DbContext(typeof(DiscountDemoDbContext))]
    [Migration("20250530183028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscountDemo.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fd3575d-e43e-49b1-b05b-16aa2947d1ea"),
                            Name = "John Doe",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a643cefd-60ff-44a3-b567-de7235525257"),
                            Name = "John Doe",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("9625e3f2-31fa-4d3a-81ab-48456372e943"),
                            Name = "John Doe",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("3c2963ab-0424-4e3d-8aef-ab0c813a08cc"),
                            Name = "John Doe",
                            Type = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
